Repository whosFritz/Rail-Insights, pull requests merged in 2024-02, with the labels that each got.

#23 improved styling
  frontend/themes/railinsights/styles.css
  src/main/bundles/README.md
  src/main/java/de/whosfritz/RailInsights/UI/Layout/MainView.java
  src/main/java/de/whosfritz/RailInsights/UI/Pages/GeneralView.java
Labels: enhancement

#34 32-inscrease-padding-check-badge
  .gitignore
  src/main/bundles/dev.bundle
  src/main/java/de/whosfritz/railinsights/ui/layout/MainView.java
Labels: enhancement

#36 fixed some minor bugs
  .gitignore
  src/main/bundles/README.md
  src/main/bundles/dev.bundle
  src/main/java/de/whosfritz/railinsights/ui/components/DarkModeToggle.java
  src/main/java/de/whosfritz/railinsights/ui/components/InfoPanel.java
  src/main/java/de/whosfritz/railinsights/ui/components/charts/CancelledDelayedOnPointPieChart.java
  src/main/java/de/whosfritz/railinsights/ui/components/charts/StoppsOverTimeChart.java
  src/main/java/de/whosfritz/railinsights/ui/pages/HomeView.java
Labels: bug, enhancement, feature

#39 fixed fucked up margin
  src/main/java/de/whosfritz/railinsights/ui/components/boards/board_components/Indicator.java
Labels: bug

#40 refactored datenschutzerklärung page
  .gitignore
  src/main/java/de/whosfritz/railinsights/ui/pages/DatenSchutzerklaerung.java
  src/main/resources/Datenschutzerklärung.html
Labels: bug, enhancement

#41 fixed darkmode datenschutz and moved to applayout
  src/main/java/de/whosfritz/railinsights/ui/layout/MainView.java
  src/main/java/de/whosfritz/railinsights/ui/pages/DatenSchutzerklaerung.java
  src/main/java/de/whosfritz/railinsights/ui/pages/ImpressumPage.java
Labels: bug

#43 added eric to impressum
  src/main/java/de/whosfritz/railinsights/ui/pages/ImpressumPage.java
Labels: bug

#51 fixed a critical bug, that excludes cancelled trips from view and calc
  src/main/java/de/whosfritz/railinsights/calculation/UniversalCalculator.java
  src/main/java/de/whosfritz/railinsights/data/dataprovider/TripDataProvider.java
  src/main/java/de/whosfritz/railinsights/data/repositories/trip_repositories/TripsRepository.java
  src/main/java/de/whosfritz/railinsights/data/services/trip_services/TripService.java
  src/main/java/de/whosfritz/railinsights/ui/components/dialogs/RemarksDialog.java
  src/main/java/de/whosfritz/railinsights/ui/pages/ConnectionPrognoseView.java
  src/main/java/de/whosfritz/railinsights/ui/pages/StationView.java
Labels: bug

#54 Cookie Darkmode, idk if darkmode is the default. I think so......
  .gitignore
  pom.xml
  src/main/java/de/whosfritz/railinsights/ui/color_scheme/ThemeBoostrapListener.java
  src/main/java/de/whosfritz/railinsights/ui/color_scheme/ThemeSelector.java
  src/main/java/de/whosfritz/railinsights/ui/color_scheme/ThemeUtil.java
  src/main/java/de/whosfritz/railinsights/ui/color_scheme/ThemeVariant.java
  src/main/java/de/whosfritz/railinsights/ui/components/DarkModeToggle.java
  src/main/java/de/whosfritz/railinsights/ui/components/DarkModeToggle3.java
  src/main/java/de/whosfritz/railinsights/ui/layout/MainView.java
  src/main/java/de/whosfritz/railinsights/ui/pages/ConnectionPrognoseView.java
Labels: bug, feature

#55 working favicon and logo
  package-lock.json
  package.json
  src/main/java/de/whosfritz/railinsights/RailInsightsApplication.java
  src/main/java/de/whosfritz/railinsights/ui/layout/MainView.java
  src/main/resources/META-INF/resources/icons/icon.png
  src/main/resources/META-INF/resources/images/darkmode.png
  src/main/resources/META-INF/resources/images/lightmode.png
  src/main/resources/webapp/icons/icon.png
Labels: feature

#56 fixed styling, removed unnecessary stylesheet and styleclasses
  frontend/themes/railinsights/styles.css
  frontend/themes/railinsights/views/stationview.css
  src/main/java/de/whosfritz/railinsights/ui/pages/StationView.java
Labels: bug, enhancement

#57 Fetch journeys works :D
  pom.xml
  src/main/java/de/whosfritz/railinsights/data/DataDispatcher.java
  src/main/java/de/whosfritz/railinsights/ui/components/Ticket.java
  src/main/java/de/whosfritz/railinsights/ui/components/TicketComponent.java
  src/main/java/de/whosfritz/railinsights/ui/pages/ConnectionPrognoseView.java
  src/main/java/de/whosfritz/railinsights/utils/TicketUtil.java
Labels: feature

#59 Fixed bug by forcing to set a unit for a highlight
  src/main/java/de/whosfritz/railinsights/ui/components/boards/StationViewDashboard.java
  src/main/java/de/whosfritz/railinsights/ui/components/boards/board_components/Highlight.java
  src/main/java/de/whosfritz/railinsights/ui/pages/HomeView.java
Labels: bug

#61 Fixed by setting local to de
  src/main/java/de/whosfritz/railinsights/ui/pages/StationView.java
Labels: bug

#63 added logos to git repo readme
  README.md
Labels: enhancement

#62 ratelimitinterceptor works. rate is limited to 1 request per second f…
  src/main/java/de/whosfritz/railinsights/rest/RateLimitInterceptor.java
  src/main/java/de/whosfritz/railinsights/rest/Request.java
Labels: bug, feature

#67 changed Hightlight Constructor and Constructor call
  src/main/java/de/whosfritz/railinsights/ui/components/boards/StationViewDashboard.java
  src/main/java/de/whosfritz/railinsights/ui/components/boards/board_components/Highlight.java
Labels: bug

#71 Update ImpressumPage.java
  src/main/java/de/whosfritz/railinsights/ui/pages/ImpressumPage.java
Labels: enhancement
