Repository whosFritz/Rail-Insights, pull requests merged in 2024-03, with the labels that each got.

#76 Better favicon and theme logo decision
  src/main/java/de/whosfritz/railinsights/ui/layout/MainView.java
  src/main/resources/META-INF/resources/icons/icon.png
  src/main/resources/META-INF/resources/images/darkmode.png
  src/main/resources/META-INF/resources/images/lightmode.png
  src/main/resources/banner.txt
  src/main/resources/webapp/icons/icon.png
Labels: enhancement

#73 46 verbindungsprognose
  frontend/themes/railinsights/styles.css
  pom.xml
  src/main/java/de/whosfritz/railinsights/calculation/UniversalCalculator.java
  src/main/java/de/whosfritz/railinsights/data/PrognoseDTO.java
  src/main/java/de/whosfritz/railinsights/data/PrognoseStateEnum.java
  src/main/java/de/whosfritz/railinsights/data/Ticket.java
  src/main/java/de/whosfritz/railinsights/data/dataprovider/JourneyDataProvider.java
  src/main/java/de/whosfritz/railinsights/data/repositories/trip_repositories/TripsRepository.java
  src/main/java/de/whosfritz/railinsights/data/services/trip_services/TripService.java
  src/main/java/de/whosfritz/railinsights/rest/RateLimitInterceptor.java
  src/main/java/de/whosfritz/railinsights/rest/controller/StationController.java
  src/main/java/de/whosfritz/railinsights/ui/components/TicketComponent.java
  src/main/java/de/whosfritz/railinsights/ui/components/boards/StationViewDashboard.java
  src/main/java/de/whosfritz/railinsights/ui/components/dialogs/ArrivalDepartureDialog.java
  src/main/java/de/whosfritz/railinsights/ui/components/dialogs/ConnectionPrognoseDialog.java
  src/main/java/de/whosfritz/railinsights/ui/components/dialogs/TripHistoryDialog.java
  src/main/java/de/whosfritz/railinsights/ui/pages/ConnectionPrognoseView.java
  src/main/java/de/whosfritz/railinsights/ui/services/DataProviderService.java
  src/main/java/de/whosfritz/railinsights/utils/TicketUtil.java
Labels: feature

#77 statistiken nach zug works
  src/main/java/de/whosfritz/railinsights/calculation/UniversalCalculator.java
  src/main/java/de/whosfritz/railinsights/data/LoadFactor.java
  src/main/java/de/whosfritz/railinsights/data/dto/TripStatistics.java
  src/main/java/de/whosfritz/railinsights/data/repositories/LineRepository.java
  src/main/java/de/whosfritz/railinsights/data/repositories/trip_repositories/TripsRepository.java
  src/main/java/de/whosfritz/railinsights/data/services/LineService.java
  src/main/java/de/whosfritz/railinsights/data/services/trip_services/TripService.java
  src/main/java/de/whosfritz/railinsights/ui/components/TicketComponent.java
  src/main/java/de/whosfritz/railinsights/ui/components/boards/StationViewDashboard.java
  src/main/java/de/whosfritz/railinsights/ui/components/boards/board_components/Highlight.java
  src/main/java/de/whosfritz/railinsights/ui/factories/notification/NotificationFactory.java
  src/main/java/de/whosfritz/railinsights/ui/layout/MainView.java
  src/main/java/de/whosfritz/railinsights/ui/pages/CancellationView.java
  src/main/java/de/whosfritz/railinsights/ui/pages/ConnectionPrognoseView.java
  src/main/java/de/whosfritz/railinsights/ui/pages/DatenSchutzerklaerungPage.java
  src/main/java/de/whosfritz/railinsights/ui/pages/StationView.java
  src/main/java/de/whosfritz/railinsights/ui/pages/TrainStatsView.java
  src/main/java/de/whosfritz/railinsights/ui/services/DataProviderService.java
Labels: feature

#78 added some margin.bottom to textfield
  src/main/java/de/whosfritz/railinsights/data/repositories/trip_repositories/TripsRepository.java
  src/main/java/de/whosfritz/railinsights/ui/components/boards/board_components/Highlight.java
  src/main/java/de/whosfritz/railinsights/ui/components/dialogs/ArrivalDepartureDialog.java
  src/main/java/de/whosfritz/railinsights/ui/components/dialogs/ConnectionPrognoseDialog.java
  src/main/java/de/whosfritz/railinsights/ui/pages/ConnectionPrognoseView.java
  src/main/java/de/whosfritz/railinsights/ui/pages/StationView.java
Labels: bug, enhancement

#75 Export is there
  pom.xml
  src/main/java/de/whosfritz/railinsights/data/repositories/trip_repositories/TripsRepository.java
  src/main/java/de/whosfritz/railinsights/data/services/csv_export_service/CSVExporterService.java
  src/main/java/de/whosfritz/railinsights/ui/pages/CsvExportView.java
Labels: feature

#79 74 efficient calculation for stats on homeview
  frontend/themes/railinsights/styles.css
  src/main/java/de/whosfritz/railinsights/data/repositories/trip_repositories/TripsRepository.java
  src/main/java/de/whosfritz/railinsights/ui/components/DarkModeToggle.java
  src/main/java/de/whosfritz/railinsights/ui/components/boards/StationViewDashboard.java
  src/main/java/de/whosfritz/railinsights/ui/components/charts/StoppsOverTimeChart.java
  src/main/java/de/whosfritz/railinsights/ui/layout/MainView.java
  src/main/java/de/whosfritz/railinsights/ui/pages/StationView.java
  src/main/java/de/whosfritz/railinsights/ui/services/DataProviderService.java
Labels: enhancement

#81 hotfixed graph glitch, fixed merge conflicts
  src/main/java/de/whosfritz/railinsights/calculation/UniversalCalculator.java
  src/main/java/de/whosfritz/railinsights/ui/components/boards/board_components/Highlight.java
  src/main/java/de/whosfritz/railinsights/ui/components/charts/StoppsOverTimeChart.java
  src/main/java/de/whosfritz/railinsights/ui/layout/MainView.java
  src/main/java/de/whosfritz/railinsights/ui/pages/CsvExportView.java
  src/main/java/de/whosfritz/railinsights/ui/pages/StationView.java
  src/main/java/de/whosfritz/railinsights/ui/pages/TrainStatsView.java
  src/main/java/de/whosfritz/railinsights/ui/services/DataProviderService.java
Labels: bug

#83 small improvements and fixes
  src/main/java/de/whosfritz/railinsights/calculation/UniversalCalculator.java
  src/main/java/de/whosfritz/railinsights/ui/components/TicketComponent.java
  src/main/java/de/whosfritz/railinsights/ui/components/boards/StationViewDashboard.java
  src/main/java/de/whosfritz/railinsights/ui/components/boards/board_components/Highlight.java
  src/main/java/de/whosfritz/railinsights/ui/components/dialogs/TripHistoryDialog.java
Labels: enhancement

#82 edited readme
  LICENSE
  README.md
Labels: enhancement

#84 Hotfix/hotfixes
  RailInsights-API-Documentation/api-doc.html
  RailInsights-API-Documentation/open-api-3.1.0.yaml
  pom.xml
  src/main/java/de/whosfritz/railinsights/rest/RateLimitInterceptor.java
  src/main/java/de/whosfritz/railinsights/rest/controller/StationController.java
  src/main/java/de/whosfritz/railinsights/rest/controller/StopController.java
  src/main/java/de/whosfritz/railinsights/rest/controller/TripController.java
  src/main/java/de/whosfritz/railinsights/rest/openapi/OpenApiConfig.java
  src/main/resources/application.properties
Labels: documentation, enhancement, security

#85 Create SECURITY.md
  SECURITY.md
Labels: enhancement, security

#87 API-Doku / Link to Sec-Policy / Styling for Grids / daily news
  RailInsights-API-Documentation/api-doc.pdf
  frontend/themes/railinsights/styles.css
  src/main/java/de/whosfritz/railinsights/data/repositories/trip_repositories/sub/RemarkRepository.java
  src/main/java/de/whosfritz/railinsights/ui/components/InfoPanel.java
  src/main/java/de/whosfritz/railinsights/ui/components/boards/board_components/HighlightSmall.java
  src/main/java/de/whosfritz/railinsights/ui/components/dialogs/ArrivalDepartureDialog.java
  src/main/java/de/whosfritz/railinsights/ui/components/dialogs/ConnectionPrognoseDialog.java
  src/main/java/de/whosfritz/railinsights/ui/components/dialogs/TripHistoryDialog.java
  src/main/java/de/whosfritz/railinsights/ui/layout/MainView.java
  src/main/java/de/whosfritz/railinsights/ui/pages/HomeView.java
  src/main/java/de/whosfritz/railinsights/ui/services/DataProviderService.java
Labels: enhancement, feature, security

#89 Rename open-api-3.1.0.yaml to open-api-3.0.1.yaml
  RailInsights-API-Documentation/open-api-3.0.1.yaml
Labels: enhancement

#94 hopefully this will fix the bug
  cypress/e2e/1-home-view/1.0-homeview-access.cy.ts
  src/main/java/de/whosfritz/railinsights/calculation/UniversalCalculator.java
  src/main/java/de/whosfritz/railinsights/data/dataprovider/JourneyDataProvider.java
  src/main/java/de/whosfritz/railinsights/data/repositories/trip_repositories/TripsRepository.java
  src/main/java/de/whosfritz/railinsights/data/services/trip_services/TripService.java
  src/main/java/de/whosfritz/railinsights/ui/components/TicketComponent.java
  src/main/java/de/whosfritz/railinsights/ui/components/dialogs/ArrivalDepartureDialog.java
  src/main/java/de/whosfritz/railinsights/ui/components/dialogs/ConnectionPrognoseDialog.java
  src/main/java/de/whosfritz/railinsights/ui/components/dialogs/RemarksDialog.java
  src/main/java/de/whosfritz/railinsights/ui/components/dialogs/TripHistoryDialog.java
  src/main/java/de/whosfritz/railinsights/ui/layout/MainView.java
  src/main/java/de/whosfritz/railinsights/ui/pages/HomeView.java
  src/main/java/de/whosfritz/railinsights/ui/pages/StationView.java
  src/main/java/de/whosfritz/railinsights/ui/pages/TrainStatsView.java
  src/main/java/de/whosfritz/railinsights/utils/TripUtil.java
  src/test/java/de/whosfritz/railinsights/utils/PercentageUtilTest.java
Labels: bug, enhancement

#95 fixed dataseries
  src/main/java/de/whosfritz/railinsights/calculation/UniversalCalculator.java
Labels: bug

#97 fix dataseries 0
  src/main/java/de/whosfritz/railinsights/calculation/UniversalCalculator.java
  src/main/java/de/whosfritz/railinsights/data/dataprovider/TripDataProvider.java
  src/main/java/de/whosfritz/railinsights/data/services/trip_services/TripService.java
  src/main/java/de/whosfritz/railinsights/ui/pages/StationView.java
  src/main/java/de/whosfritz/railinsights/ui/pages/TrainStatsView.java
  src/main/java/de/whosfritz/railinsights/utils/TripUtil.java
Labels: bug

#104 changed boadge color
  src/main/java/de/whosfritz/railinsights/ui/components/boards/board_components/Highlight.java
Labels: enhancement

#106 Feature/chart percentages overtime
  cypress.config.ts
  cypress/e2e/spec.cy.ts
  cypress/fixtures/example.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  src/main/java/de/whosfritz/railinsights/data/dataprovider/JourneyDataProvider.java
  src/main/java/de/whosfritz/railinsights/data/dto/PercentageDataSeriesDTO.java
  src/main/java/de/whosfritz/railinsights/data/dto/TripPercentageDTO.java
  src/main/java/de/whosfritz/railinsights/data/repositories/trip_repositories/TripsRepository.java
  src/main/java/de/whosfritz/railinsights/data/services/trip_services/TripService.java
  src/main/java/de/whosfritz/railinsights/ui/components/charts/PercentageTimeChart.java
  src/main/java/de/whosfritz/railinsights/ui/components/dialogs/ConnectionPrognoseDialog.java
  src/main/java/de/whosfritz/railinsights/ui/pages/HomeView.java
  src/main/java/de/whosfritz/railinsights/ui/services/DataProviderService.java
  src/main/java/de/whosfritz/railinsights/utils/TripUtil.java
  vite.config.ts
Labels: feature

#110 removed the code
  src/main/java/de/whosfritz/railinsights/ui/components/boards/board_components/Highlight.java
Labels: bug

#107 Tests/cypress
  cypress/e2e/1-home-view/1.0-homeview-access.cy.ts
  cypress/e2e/component-tests/dark_mode_toggle_test.cy.js
  cypress/e2e/component-tests/sidebar_test.cy.js
  cypress/e2e/spec.cy.ts
  cypress/e2e/view-tests/homeview_test.cy.js
  tsconfig.json
Labels: testing

#111 namensauflösung gefixed und entsprechend der funktionalität angepasst
  src/main/java/de/whosfritz/railinsights/ui/components/boards/board_components/Highlight.java
  src/main/java/de/whosfritz/railinsights/ui/layout/MainView.java
  src/main/resources/META-INF/resources/images/darkmode.png
  src/main/resources/META-INF/resources/images/lightmode.png
  tsconfig.json
Labels: bug

#113 fixed NP error
  src/main/java/de/whosfritz/railinsights/calculation/UniversalCalculator.java
Labels: bug

#114 fixed button text no color
  src/main/java/de/whosfritz/railinsights/ui/pages/TrainStatsView.java
Labels: bug

#115 fixed badge color
  frontend/themes/railinsights/styles.css
  src/main/java/de/whosfritz/railinsights/ui/pages/TrainStatsView.java
Labels: bug, enhancement

#118 prototype delay View
  src/main/java/de/whosfritz/railinsights/calculation/UniversalCalculator.java
  src/main/java/de/whosfritz/railinsights/data/repositories/LineRepository.java
  src/main/java/de/whosfritz/railinsights/data/repositories/trip_repositories/TripsRepository.java
  src/main/java/de/whosfritz/railinsights/data/services/LineService.java
  src/main/java/de/whosfritz/railinsights/data/services/trip_services/TripService.java
  src/main/java/de/whosfritz/railinsights/ui/components/charts/DailyDelayChart.java
  src/main/java/de/whosfritz/railinsights/ui/layout/MainView.java
  src/main/java/de/whosfritz/railinsights/ui/pages/DelayedView.java
  src/main/java/de/whosfritz/railinsights/ui/pages/TrainStatsView.java
  src/main/java/de/whosfritz/railinsights/ui/services/DataProviderService.java
Labels: feature

#120 45 verspätungsview
  frontend/themes/railinsights/styles.css
  src/main/java/de/whosfritz/railinsights/calculation/UniversalCalculator.java
  src/main/java/de/whosfritz/railinsights/data/repositories/trip_repositories/TripsRepository.java
  src/main/java/de/whosfritz/railinsights/data/services/trip_services/TripService.java
  src/main/java/de/whosfritz/railinsights/ui/layout/MainView.java
  src/main/java/de/whosfritz/railinsights/ui/pages/DelayedView.java
  src/main/java/de/whosfritz/railinsights/ui/pages/StationView.java
  src/main/java/de/whosfritz/railinsights/ui/pages/TrainStatsView.java
Labels: bug, feature, high-prio

#122 added SVG Export
  src/main/java/de/whosfritz/railinsights/ui/components/charts/DailyDelayChart.java
  src/main/java/de/whosfritz/railinsights/ui/pages/TrainStatsView.java
Labels: feature

#126 fix insight view
  src/main/java/de/whosfritz/railinsights/data/repositories/trip_repositories/TripsRepository.java
  src/main/java/de/whosfritz/railinsights/data/services/trip_services/TripService.java
  src/main/java/de/whosfritz/railinsights/ui/pages/DelayedView.java
Labels: bug

#127 feature showing calc time delayed time
  src/main/java/de/whosfritz/railinsights/ui/pages/DelayedView.java
Labels: feature
